### ISSUE TITLE
Ignores selections spanning multiple lines

### ISSUE THREAD

**Issue by damiong28** [viablelab/vscode-capitalize#2]
This is the only use case I have for this tool, is to capitalize multiple lines at a time.

**Comment by mrwest808** [comment]
Since titles usually span a single line, I delibaretly opted for a no-op when a selection spans multiple lines. Perhaps we might as well just allow running this with multiple lines selected, but have you tried using multiple cursors to solve this use case?

**Comment by damiong28** [comment]
@mrwest808 Looks like that works! Thanks for the reply.
