### ISSUE TITLE
Update version of "title" package to latest

### ISSUE THREAD

**Issue by rbjoern84** [viablelab/vscode-capitalize#3]
While using the plugin I recognized, that the results are not always consistent to the output of the current version of `title` package. Here an example:

VS Code Plugin (uses older version of `title`): **"Created at"**

Current version of `title`: **"Create At"**

The rule behind I found on Wikipedia:

> Always capitalize the first and last words of titles and subtitles (overrides the rules above).

See [article](https://en.wikipedia.org/wiki/Title_case).

Maybe updating the version will fix this issue?

**Comment by mrwest808** [comment]
Thanks for letting me know, I'll try updating the version in the upcoming days.

**Comment by mrwest808** [comment]
Fixed in version 0.2.1.
